### ISSUE TITLE
Inference with a still image

### ISSUE THREAD

**Issue by tucan9389** [tucan9389/PoseEstimation-TFLiteSwift#13]
## Purpose

Implement to import an image and inference

## Tasks

- [x] Create tabbar for separating live captured image inference - #11
- [x] Get an image from device's photo album - #14
- [ ] Inference the image - #25 
- [ ] Draw the result of inference - #25
